basePath: /
host: localhost:8080
info:
  contact:
    name: Minh Thuong
  description: This is a sample server Cake ATS API server.
  title: Cake ATS API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
